apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-java-maven
  namespace: cicd-java-maven  # Make sure this namespace exists!
  labels:
    app: cicd-java-maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-java-maven
  template:
    metadata:
      labels:
        app: cicd-java-maven
    spec:
      containers:
        - name: cicd-java-maven
          image: dash18/cicd-java-maven
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
