apiVersion: v1
kind: Service
metadata:
  name: cicd-java-service
  namespace: cicd-java-maven
spec:
  type: NodePort
  selector:
    app: cicd-java-maven
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      
