apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: cicd-java-maven
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30036  # Optional: Kubernetes will choose one if you skip this

